//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace LibHelper.SaveDsDeliNote {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ICT_WS_pps_DS_saveDS_DELI_NOTE_G_EMEIA_Binder", Namespace="http://EDI-UMISMWSStag.luxshare.com.cn/ICT_WS.pps.DS:saveDS_DELI_NOTE_G_EMEIA")]
    public partial class ICT_WSppsDSsaveDS_DELI_NOTE_G_EMEIA : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback saveDS_DELI_NOTE_G_EMEIAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ICT_WSppsDSsaveDS_DELI_NOTE_G_EMEIA() {
            this.Url = global::LibHelper.Properties.Settings.Default.LibHelper_SaveDsDeliNote_ICT_WS_pps_DS_saveDS_DELI_NOTE_G_EMEIA;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event saveDS_DELI_NOTE_G_EMEIACompletedEventHandler saveDS_DELI_NOTE_G_EMEIACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ICT_WS_pps_DS_saveDS_DELI_NOTE_G_EMEIA_Binder_saveDS_DELI_NOTE_G_EMEIA", RequestNamespace="http://EDI-UMISMWSStag.luxshare.com.cn/ICT_WS.pps.DS:saveDS_DELI_NOTE_G_EMEIA", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void saveDS_DELI_NOTE_G_EMEIA([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string shipmentID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string acDN) {
            this.Invoke("saveDS_DELI_NOTE_G_EMEIA", new object[] {
                        shipmentID,
                        acDN});
        }
        
        /// <remarks/>
        public void saveDS_DELI_NOTE_G_EMEIAAsync(string shipmentID, string acDN) {
            this.saveDS_DELI_NOTE_G_EMEIAAsync(shipmentID, acDN, null);
        }
        
        /// <remarks/>
        public void saveDS_DELI_NOTE_G_EMEIAAsync(string shipmentID, string acDN, object userState) {
            if ((this.saveDS_DELI_NOTE_G_EMEIAOperationCompleted == null)) {
                this.saveDS_DELI_NOTE_G_EMEIAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveDS_DELI_NOTE_G_EMEIAOperationCompleted);
            }
            this.InvokeAsync("saveDS_DELI_NOTE_G_EMEIA", new object[] {
                        shipmentID,
                        acDN}, this.saveDS_DELI_NOTE_G_EMEIAOperationCompleted, userState);
        }
        
        private void OnsaveDS_DELI_NOTE_G_EMEIAOperationCompleted(object arg) {
            if ((this.saveDS_DELI_NOTE_G_EMEIACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveDS_DELI_NOTE_G_EMEIACompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void saveDS_DELI_NOTE_G_EMEIACompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591