//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.12.40.249:5556/ws/ICT_WS.oa:getUPS_HAWB_ws/ICT_WS_oa_getUPS_HAWB_ws_Por" +
            "t")]
        public string LibHelper_UpsHawb_ICT_WS_oa_getUPS_HAWB_ws {
            get {
                return ((string)(this["LibHelper_UpsHawb_ICT_WS_oa_getUPS_HAWB_ws"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.12.40.249:5556/ws/ICT_WS.pps.DS:saveDS_DELI_NOTE_G_EMEIA/ICT_WS_pps_DS_" +
            "saveDS_DELI_NOTE_G_EMEIA_Port")]
        public string LibHelper_SaveDsDeliNote_ICT_WS_pps_DS_saveDS_DELI_NOTE_G_EMEIA {
            get {
                return ((string)(this["LibHelper_SaveDsDeliNote_ICT_WS_pps_DS_saveDS_DELI_NOTE_G_EMEIA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.12.40.249:5556/ws/ICT_WS.pps.DS:genShippingDocLabel/ICT_WS_pps_DS_genSh" +
            "ippingDocLabel_Port")]
        public string LibHelper_ToEdiByInfoInPick_ICT_WS_pps_DS_genShippingDocLabel {
            get {
                return ((string)(this["LibHelper_ToEdiByInfoInPick_ICT_WS_pps_DS_genShippingDocLabel"]));
            }
        }
    }
}
