using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OracleClient;
using System.Linq;
using System.Text;

namespace Write_ReaderTxt
{
    public class DHL_ECX_Write
    {
        public void DhlExcWrite(string DN, string DN_Line, string path, string fileName, string cartonNo)
        {
            DataSet dataSet = new DataSet();
            if (string.IsNullOrEmpty(cartonNo))
            {
                #region SQL
                string sql = @"SELECT
                                 '1' AS e1,
                               --'' AS e2,
                               --'' as e3,
                               --'' as e4,
                                 'SPS 2.03' AS e5,
                                 'SPS' AS e6,
                                 '' AS e7,
                                 '' AS e8,
                                 '' AS e9,
                                 '' AS e10,
                                 '' AS e11,
                                 A.hawb AS e12,
                                 'EIN' AS e13,
                                 '' AS e14,
                                 '' AS e15,
                                 A.accout_num AS e16,
                                 'ADI c/o Syncreon' AS e17,
                                 'Syncreon' AS e18,
                                 'Van Hilststraat 23' AS e19,
                                 '.' AS e20,
                                 '' AS e21,
                                 'WAALWIJK' AS e22,
                                 '' AS e23,
                                 '5145 RK' AS e24,
                                 'NETHERLANDS' AS e25,
                                 'NL' AS e26,
                                 A.ac_dn AS e27,
                                 '+31(0)416711300' AS e28,
                                 '' AS e29,
                                 '' AS e30,
                                 '' AS e31,
                                 '' AS e32,
                                 'N' AS e33,
                                 'USD' AS e34,
                                 A.accout_num AS e35,
                                 A.st_name AS e36,
                                 A.st_name AS e37,
                                 NVL(A.st_addr1,'.') AS e38,
                                 NVL(A.st_addr2,'.') AS e39,
                                 A.st_addr3 AS e40,
                                 A.st_city AS e41,
                                 A.st_province AS e42,
                                 A.st_postal AS e43,
                                 '' AS e44,
                                 A.st_country_code AS e45,
                                 NVL(A.rece_c_tele,'.') AS e46,
                                 '' AS e47,
                                 '' AS e48,
                                 '' AS e49,
                                 '' AS e50,
                                 'N' AS e51,
                                 '' AS e52,
                                 '' AS e53,
                                 'U' AS e54,
                                 'U' AS e55,
                                 TO_CHAR(A.ship_date,'YYYYMMDD') AS e56, 
                                 TO_CHAR(A.ship_date,'HHmm') AS e57,  
                                 '' AS e58,
                                 '' AS e59,
                                 A.carton_count AS e60,
                                 'Y' AS e61,
                                 A.dn_total_weight AS e62,
                                 '' AS e63,
                                 '' AS e64,
                                 '' AS e65,
                                 A.shipment_total_value AS e66,
                                 '0' AS e67,
                                 '' AS e68,
                                 '' AS e69,
                                 '' AS e70,
                                 '' AS e71,
                                 '' AS e72,
                                 '' AS e73,
                                 '' AS e74,
                                 '' AS e75,
                                 '' AS e76,
                                 '' AS e77,
                                 '' AS e78,
                                 '' AS e79,
                                 '' AS e80,
                                 '' AS e81,
                                 'N' AS e82,
                                 '' AS e83,
                                 '0' AS e84,
                                 '' AS e85,
                                 '' AS e86,
                                 '' AS e87,
                                 'N' AS e88,
                                 '' AS e89,
                                 '0' AS e90,
                                 '' AS e91,
                                 '' AS e92,
                                 '' AS e93,
                                 '' AS e94,
                                 '' AS e95,
                                 '' AS e96,
                                 '' AS e97,
                               --'' AS e98,
                               --'' AS e99,
                                 '2' AS e100,
                                 B.dn_ship_content AS e101,
                                 '' as e102,
                               --'' as e103,
                               --'' as e104,
                                 '0' AS e105,
                               --'' as e106,
                               --'' as e107,
                               --'' as e108,
                               --'' as e109,
                               --'' as e110,
                               --'' as e111,
                               --'' as e112,
                               --'' as e113,
                                 '0' AS e114,
                                 'N' AS e115,
                                 '' AS e116,
                                 '' AS e117,
                                 '' AS e118,
                                 '' AS e119,
                                 '' AS e120,
                                 A.trade_term AS e121,
                                 '' AS e122,
                                 '' AS e123,
                                 '' AS e124,
                                 '' AS e125,
                               --''' as e126,
                               --''' as e127,
                               --''' as e128,
                               --''' as e129,
                               --''' as e130,
                               --''' as e131,
                               --''' as e132,
                               --''' as e133,
                               --''' as e134,
                               --''' as e135,
                               --''' as e136,
                               --''' as e137,
                               --''' as e138,
                               --''' as e139,
                               --''' as e140,
                               --''' as e141,
                               --''' as e142,
                               --''' as e143,
                               --''' as e144,
                               --''' as e145,
                               --''' as e146,
                               --''' as e147,
                               --''' as e148,
                               --''' as e149,
                               --''' as e150,
                               --''' as e151,
                               --''' as e152,
                               --''' as e153,
                               --''' as e154,
                               --''' as e155,
                               --''' as e156,
                                 '3' AS e157,
                                 A.ac_dn AS e158,
                                 '' AS e159,
                                 '' AS e160,
                                 '' AS e161,
                                 '' AS e162,
                                 '' AS e163,
                               --'' as e164,
                               --'' as e165,
                               --A.carton_count AS e166,
                                 '1' AS e166,
                                 b.connote_no AS e167,
                                 b.box_weight AS e168,
                                 '' AS e169,
                                 '' AS e170,
                                 '' AS e171,
                                 '' AS e172,
                                 '' AS e173,
                                 'KG' AS e174,
                                 b.ac_pn AS e175,
                                 '' AS e176,
                                 '' AS e177,
                                 '' AS e178,
                                 '3' AS e179,
                                 '' AS e180,
                                 '' AS e181,
                                 nvl(b.carton_sequnece,0)
                                  || '/'
                                  || nvl(A.carton_count,0) AS e182,
                                 '' AS e183,
                                 '' AS e184,
                                 '' AS e185
                             FROM ppsuser.ict_lps_header a
                             JOIN ppsuser.ict_lps_line b 
                               ON A.msg_id = b.msg_id 
                            WHERE b.ac_dn = :ac_dn and b.ac_dn_line=:ac_dn_line 
                            order by TO_NUMBER(b.carton_sequnece) desc NULLS LAST"; 
                #endregion
                object[][] parameterArray = new object[2][];
                parameterArray[0] = new object[] { ParameterDirection.Input, OracleType.VarChar, "ac_dn", DN };
                parameterArray[1] = new object[] { ParameterDirection.Input, OracleType.VarChar, "ac_dn_line", DN_Line };

                dataSet = ClientUtils.ExecuteSQL(sql, parameterArray);
            }
            else
            {
                #region SQL
                string sql = @"SELECT
                                 '1' AS e1,
                               --'' AS e2,
                               --'' as e3,
                               --'' as e4,
                                 'SPS 2.03' AS e5,
                                 'SPS' AS e6,
                                 '' AS e7,
                                 '' AS e8,
                                 '' AS e9,
                                 '' AS e10,
                                 '' AS e11,
                                 A.hawb AS e12,
                                 'EIN' AS e13,
                                 '' AS e14,
                                 '' AS e15,
                                 A.accout_num AS e16,
                                 'ADI c/o Syncreon' AS e17,
                                 'Syncreon' AS e18,
                                 'Van Hilststraat 23' AS e19,
                                 '.' AS e20,
                                 '' AS e21,
                                 'WAALWIJK' AS e22,
                                 '' AS e23,
                                 '5145 RK' AS e24,
                                 'NETHERLANDS' AS e25,
                                 'NL' AS e26,
                                 A.ac_dn AS e27,
                                 '+31(0)416711300' AS e28,
                                 '' AS e29,
                                 '' AS e30,
                                 '' AS e31,
                                 '' AS e32,
                                 'N' AS e33,
                                 'USD' AS e34,
                                 A.accout_num AS e35,
                                 A.st_name AS e36,
                                 A.st_name AS e37,
                                 NVL(A.st_addr1,'.') AS e38,
                                 NVL(A.st_addr2,'.') AS e39,
                                 A.st_addr3 AS e40,
                                 A.st_city AS e41,
                                 A.st_province AS e42,
                                 A.st_postal AS e43,
                                 '' AS e44,
                                 A.st_country_code AS e45,
                                 NVL(A.rece_c_tele,'.') AS e46,
                                 '' AS e47,
                                 '' AS e48,
                                 '' AS e49,
                                 '' AS e50,
                                 'N' AS e51,
                                 '' AS e52,
                                 '' AS e53,
                                 'U' AS e54,
                                 'U' AS e55,
                                 TO_CHAR(A.ship_date,'YYYYMMDD') AS e56, 
                                 TO_CHAR(A.ship_date,'HHmm') AS e57,  
                                 '' AS e58,
                                 '' AS e59,
                                 A.carton_count AS e60,
                                 'Y' AS e61,
                                 A.dn_total_weight AS e62,
                                 '' AS e63,
                                 '' AS e64,
                                 '' AS e65,
                                 A.shipment_total_value AS e66,
                                 '0' AS e67,
                                 '' AS e68,
                                 '' AS e69,
                                 '' AS e70,
                                 '' AS e71,
                                 '' AS e72,
                                 '' AS e73,
                                 '' AS e74,
                                 '' AS e75,
                                 '' AS e76,
                                 '' AS e77,
                                 '' AS e78,
                                 '' AS e79,
                                 '' AS e80,
                                 '' AS e81,
                                 'N' AS e82,
                                 '' AS e83,
                                 '0' AS e84,
                                 '' AS e85,
                                 '' AS e86,
                                 '' AS e87,
                                 'N' AS e88,
                                 '' AS e89,
                                 '0' AS e90,
                                 '' AS e91,
                                 '' AS e92,
                                 '' AS e93,
                                 '' AS e94,
                                 '' AS e95,
                                 '' AS e96,
                                 '' AS e97,
                               --'' AS e98,
                               --'' AS e99,
                                 '2' AS e100,
                                 B.dn_ship_content AS e101,
                                 '' as e102,
                               --'' as e103,
                               --'' as e104,
                                 '0' AS e105,
                               --'' as e106,
                               --'' as e107,
                               --'' as e108,
                               --'' as e109,
                               --'' as e110,
                               --'' as e111,
                               --'' as e112,
                               --'' as e113,
                                 '0' AS e114,
                                 'N' AS e115,
                                 '' AS e116,
                                 '' AS e117,
                                 '' AS e118,
                                 '' AS e119,
                                 '' AS e120,
                                 A.trade_term AS e121,
                                 '' AS e122,
                                 '' AS e123,
                                 '' AS e124,
                                 '' AS e125,
                               --''' as e126,
                               --''' as e127,
                               --''' as e128,
                               --''' as e129,
                               --''' as e130,
                               --''' as e131,
                               --''' as e132,
                               --''' as e133,
                               --''' as e134,
                               --''' as e135,
                               --''' as e136,
                               --''' as e137,
                               --''' as e138,
                               --''' as e139,
                               --''' as e140,
                               --''' as e141,
                               --''' as e142,
                               --''' as e143,
                               --''' as e144,
                               --''' as e145,
                               --''' as e146,
                               --''' as e147,
                               --''' as e148,
                               --''' as e149,
                               --''' as e150,
                               --''' as e151,
                               --''' as e152,
                               --''' as e153,
                               --''' as e154,
                               --''' as e155,
                               --''' as e156,
                                 '3' AS e157,
                                 A.ac_dn AS e158,
                                 '' AS e159,
                                 '' AS e160,
                                 '' AS e161,
                                 '' AS e162,
                                 '' AS e163,
                               --'' as e164,
                               --'' as e165,
                               --A.carton_count AS e166,
                                 '1' AS e166,
                                 b.connote_no AS e167,
                                 b.box_weight AS e168,
                                 '' AS e169,
                                 '' AS e170,
                                 '' AS e171,
                                 '' AS e172,
                                 '' AS e173,
                                 'KG' AS e174,
                                 b.ac_pn AS e175,
                                 '' AS e176,
                                 '' AS e177,
                                 '' AS e178,
                                 '3' AS e179,
                                 '' AS e180,
                                 '' AS e181,
                                 nvl(b.carton_sequnece,0)
                                  || '/'
                                  || nvl(A.carton_count,0) AS e182,
                                 '' AS e183,
                                 '' AS e184,
                                 '' AS e185
                             FROM ppsuser.ict_lps_header a
                             JOIN ppsuser.ict_lps_line b 
                               ON A.msg_id = b.msg_id 
                            WHERE b.ac_dn = :ac_dn 
                              AND b.ac_dn_line= :ac_dn_line 
                              AND b.carton_id = :catonNo
                            order by TO_NUMBER(b.carton_sequnece) desc NULLS LAST"; 
                #endregion

                object[][] parameterArray = new object[3][];
                parameterArray[0] = new object[] { ParameterDirection.Input, OracleType.VarChar, "ac_dn", DN };
                parameterArray[1] = new object[] { ParameterDirection.Input, OracleType.VarChar, "ac_dn_line", DN_Line };
                parameterArray[2] = new object[] { ParameterDirection.Input, OracleType.VarChar, "catonNo", cartonNo };
                dataSet = ClientUtils.ExecuteSQL(sql, parameterArray);
            }
            StringBuilder stringBuilder = new StringBuilder();
            //int i = 1;
            if (dataSet != null && dataSet.Tables[0] != null && dataSet.Tables[0].Rows.Count > 0)
            {
                bool lineFlag = true;
                foreach (DataColumn dataColumn in dataSet.Tables[0].Columns)
                {
                    //stringBuilder.Append(dataSet.Tables[0].Rows[0][dataColumn].ToString() + "\r\n");
                    stringBuilder.Append(dataSet.Tables[0].Rows[0][dataColumn].ToString() + "|");
                    if (lineFlag)
                    {
                        stringBuilder.Append(Environment.NewLine);
                        lineFlag = false;
                    }
                }
            }

            string result = string.Empty;
            if (!string.IsNullOrEmpty(stringBuilder.ToString()))
            {
                result = stringBuilder.ToString().Substring(0, stringBuilder.Length - 1);
            }
            if (!System.IO.Directory.Exists(path))
            {
                System.IO.Directory.CreateDirectory(path);
            }
            WriteFile wf = new WriteFile();
            wf.writeFile(path, fileName, result);
        }
    }
}
