//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace LibHelper.UpsHawb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ICT_WS_oa_getUPS_HAWB_ws_Binder", Namespace="http://DG1U-ESBIS-SVR01.luxshare.com.cn/ICT_WS.oa:getUPS_HAWB_ws")]
    public partial class ICT_WSoagetUPS_HAWB_ws : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getUPS_HAWB_wsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ICT_WSoagetUPS_HAWB_ws() {
            this.Url = global::LibHelper.Properties.Settings.Default.LibHelper_UpsHawb_ICT_WS_oa_getUPS_HAWB_ws;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getUPS_HAWB_wsCompletedEventHandler getUPS_HAWB_wsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ICT_WS_oa_getUPS_HAWB_ws_Binder_getUPS_HAWB_ws", RequestNamespace="http://DG1U-ESBIS-SVR01.luxshare.com.cn/ICT_WS.oa:getUPS_HAWB_ws", ResponseNamespace="http://DG1U-ESBIS-SVR01.luxshare.com.cn/ICT_WS.oa:getUPS_HAWB_ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("hawb_tran", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string getUPS_HAWB_ws([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string carrierCode, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string parcelAccount, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string serviceLevel) {
            object[] results = this.Invoke("getUPS_HAWB_ws", new object[] {
                        carrierCode,
                        parcelAccount,
                        serviceLevel});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getUPS_HAWB_wsAsync(string carrierCode, string parcelAccount, string serviceLevel) {
            this.getUPS_HAWB_wsAsync(carrierCode, parcelAccount, serviceLevel, null);
        }
        
        /// <remarks/>
        public void getUPS_HAWB_wsAsync(string carrierCode, string parcelAccount, string serviceLevel, object userState) {
            if ((this.getUPS_HAWB_wsOperationCompleted == null)) {
                this.getUPS_HAWB_wsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUPS_HAWB_wsOperationCompleted);
            }
            this.InvokeAsync("getUPS_HAWB_ws", new object[] {
                        carrierCode,
                        parcelAccount,
                        serviceLevel}, this.getUPS_HAWB_wsOperationCompleted, userState);
        }
        
        private void OngetUPS_HAWB_wsOperationCompleted(object arg) {
            if ((this.getUPS_HAWB_wsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUPS_HAWB_wsCompleted(this, new getUPS_HAWB_wsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getUPS_HAWB_wsCompletedEventHandler(object sender, getUPS_HAWB_wsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUPS_HAWB_wsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUPS_HAWB_wsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591