//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace LibHelper.ToEdiByInfoInPick {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ICT_WS_pps_DS_genShippingDocLabel_Binder", Namespace="http://DG1U-ESBIS-SVR01.luxshare.com.cn/ICT_WS.pps.DS:genShippingDocLabel")]
    public partial class ICT_WSppsDSgenShippingDocLabel : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback genShippingDocLabel_wsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ICT_WSppsDSgenShippingDocLabel() {
            this.Url = global::LibHelper.Properties.Settings.Default.LibHelper_ToEdiByInfoInPick_ICT_WS_pps_DS_genShippingDocLabel;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event genShippingDocLabel_wsCompletedEventHandler genShippingDocLabel_wsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ICT_WS_pps_DS_genShippingDocLabel_Binder_genShippingDocLabel_ws", RequestNamespace="http://DG1U-ESBIS-SVR01.luxshare.com.cn/ICT_WS.pps.DS:genShippingDocLabel", ResponseNamespace="http://DG1U-ESBIS-SVR01.luxshare.com.cn/ICT_WS.pps.DS:genShippingDocLabel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("responseString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string genShippingDocLabel_ws([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string SHIPMENT_ID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string REGION, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string SHIP_TYPE, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] out string @string) {
            object[] results = this.Invoke("genShippingDocLabel_ws", new object[] {
                        SHIPMENT_ID,
                        REGION,
                        SHIP_TYPE});
            @string = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void genShippingDocLabel_wsAsync(string SHIPMENT_ID, string REGION, string SHIP_TYPE) {
            this.genShippingDocLabel_wsAsync(SHIPMENT_ID, REGION, SHIP_TYPE, null);
        }
        
        /// <remarks/>
        public void genShippingDocLabel_wsAsync(string SHIPMENT_ID, string REGION, string SHIP_TYPE, object userState) {
            if ((this.genShippingDocLabel_wsOperationCompleted == null)) {
                this.genShippingDocLabel_wsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenShippingDocLabel_wsOperationCompleted);
            }
            this.InvokeAsync("genShippingDocLabel_ws", new object[] {
                        SHIPMENT_ID,
                        REGION,
                        SHIP_TYPE}, this.genShippingDocLabel_wsOperationCompleted, userState);
        }
        
        private void OngenShippingDocLabel_wsOperationCompleted(object arg) {
            if ((this.genShippingDocLabel_wsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.genShippingDocLabel_wsCompleted(this, new genShippingDocLabel_wsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void genShippingDocLabel_wsCompletedEventHandler(object sender, genShippingDocLabel_wsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class genShippingDocLabel_wsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal genShippingDocLabel_wsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string @string {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591